### ISSUE TITLE
viacjazycnost

### ISSUE THREAD

**Issue by havlasme** [1zizu0/ZdraveTelo#2]
Chceme naozaj riešiť podporu viacerých jazykov, prepínaním pomocou tlačidiel/vlajok v GUI?
Android má zabudovanú podporu prispôsobenia jazyka aplikácie, jazyku celého systému, tzn. pokiaľ mám celý systém v slovenčine, tak aplikácia bude používať slovenský preklad (pokiaľ je dostupný) a v prípade ak mám systém v inom jazyku, ktorý nie je podporovaný aplikáciou, tak sa bude používať defaultný jazyk (štandardne angličtina). 
Vyššie popísanú opísaná funkcionalitu som implementoval v commite 096ef204eee50ea995751f3ecaf1c0e5f0f21dce.
Pokiaľ súhlasíte s tým aby bola podpora rôznych jazykov implementovaná týmto spôsobom, tak by bolo vhodné z GUI odstrániť momentálne existujúce tlačidlá/vlajky. V opačnom prípade je možné implementovať prepínanie jazyku pomocou týchto tlačidiel, ale nejedná sa o štandardnú vec podporovanú android platformou, čo môže spôsobiť komplikácie pri programovaní.

**Comment by mhalgas** [comment]
Poriadku ak to nieje podporovanie adroidovou platformou a robilo by to
paseku môžme to odstrániť.

2015-03-12 2:28 GMT+01:00 tomashavlas notifications@github.com:
